name: Run Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install update
        run: sudo apt update -y 

      - name: install nginx
        run: sudo apt install nginx -y

      - name: Test landing page nginx
        run: curl localhost
